image:
  repository: ghcr.io/elhadj-cloud-lab/produit_back
  tag: prod-d6c15ce

replicaCount: 2

env:
  - name: SPRING_DATASOURCE_URL_PROD
    value: jdbc:postgresql://postgres-produit-postgresql:5432/produit_db
  - name: SPRING_DATASOURCE_USERNAME
    value: produit_user
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres-produit-credentials
        key: password

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
