image:
  repository: ghcr.io/elhadj-cloud-lab/produit_back
  tag: prod-d6c15ce

replicaCount: 2

env:
  - name: SPRING_DATASOURCE_URL_PROD
    value: jdbc:postgresql://postgres-produit-postgresql:5432/produit_db
  - name: SPRING_DATASOURCE_USERNAME
    value: produit_user
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres-produit-credentials
        key: password

initContainers:
  - name: wait-for-db
    image: busybox:1.36
    command:
      - sh
      - -c
      - >-
        echo Waiting for postgres-produit-postgresql:5432...;
        for i in $(seq 1 120); do
          nc -z postgres-produit-postgresql 5432 && exit 0;
          sleep 2;
        done;
        echo DB not reachable;
        exit 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
