replicaCount: 1

image:
  repository: ghcr.io/elhadj-cloud-lab/produits_front
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

containerPort: 80

resources: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  host: ""
  pathType: Prefix
  tls: []
  backend:
    serviceName: produit-back
    servicePort: 80
