apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../postgres-auth/sealedsecret-prod.yaml
  - ../../postgres-produit/sealedsecret-prod.yaml
  - ../../authentification_service/sealedsecret-prod.yaml
