apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentification-service-secrets
  namespace: dev
spec:
  encryptedData:
    jwt-secret: AgAtuQrKFw+WwpP5mq2ToRZGFfHDI3rXsbgeN2u0wg+5peIrDwUbhIC4LHOOoVNE5fjnHJvl1fIR1/x183RauZ9F/ycRNf1FgHSjKYGnBR4qDsJ5pr/Av7J3yFQouB5vQvGvk7pagWBOjvYVMprs4eKSlEQEN0BW+7HyzXbwKCZrHSmznjZdAIkiW60ZVX7W4zZ3Rd7PH3sDrnztWNjKp4k1wT1LyOfetqvAruVe2W1e3eanr2btnTKuq+HrIDJM/rgP5kCJUzUWX3lzfOqq8fvvHzbp8KJ81m1V56o68fZE49EdTRtsqvdpOTzExwwn0UyJy3t+6iQsvQpnk5h0n5HESwTjLGm8ohs/cztLq4iipvej8RnndGqGA42/QYd6Xcef+EYt3O16nbEnZJ0Ez1jUJYiIJfS0Bsxk6GkFUiwTe5efVrzxS03OF+rRSu589BvujC6HnhyNfR4nEozrcqF0pgEOr95cdtM0YIKbpQRFxLXQ+8vAovpFrF/yWWaCd5S07jkiyfiPkTynYKO/HPGNjYBBArk0pxjjJzMoeZNhcXqmpWoMaoNt9Mixa1jNFnngsxzhJ22royCxOZrOtbMlkiDOYCjWDW0vtOCVNsGMrowGxUEYJbrU9DIUeBW3dJqbF5GnGLDIVeG7ymJpcOK4IOOX0niPDgFwq/POOdGR/moTsStXfuPs47BuJ4mH0fFGgwdz95+2GguznYLlPH47/SvUsErpkzw=
  template:
    metadata:
      creationTimestamp: null
      name: authentification-service-secrets
      namespace: dev

