apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentification-service-secrets
  namespace: prod
spec:
  encryptedData:
    jwt-secret: AgANlYQceaDU3bQZwP2ZkXfZFs0YYfJa9TPOPGN1LY6qpZMzK42ZVZTNEg5lTGHVP3jACT+jFzJidg/9zMu5UlK5bg84uWT5LOMeOIyil2UJYbiVfw7UcwUWVNwsoHup2FemSenKksFSPRM3WXYNk5KTy6Mo0kAp+ZOI8qIuGbPIIUXJt1jDy4DSON7Wp1p4WBJ/oapCsjiq7Ko3vsbnsaxK22AqaI9diMH090fXU4m5u1crJ/2ns1RpF7DicLwnM/8BwPgjgwB0GlcwjIgAaFoEiDhoGzSNQAHcrHoafsm7KlVTD0scVp3EWnn3ISvaF4REGLgWsQo9CpVXOofKy7Lu97fdlikrwildhiD5rUuoWRkB2CZshNWGVlg6R+BTFa05VC8LKiitruL3i+Rq8KPVKQaGy/k2Jov5TfAZF48/kkzQJyFBsxmUihUZm4AMzHJlS85t0mwM88O36/tiFGdD+OGgLtWXGYCAELwpvh+ZJ4diVQHzRsCwqNzwsPhJ5UIUE1N52cl2FMmG91VMPKkM2gJrIL8xnjTGpriXUq57bofn4PrIhVaVkepeuSLWx2rv+giC86xBhLqB8+GnocDPy4tS3tfNXQcWvqukwUfAAI+rfCC4uVdTgUk90m+VT4gB6yrj0dWTiX5R/ZIXfJYDXXqGJ0uzFcbuYJnK7I9twfqcwnXjKROAbhwL8Inx0KyQYFfqOktVYqUlnoG/IbwNPKqfgylU794Z
  template:
    metadata:
      creationTimestamp: null
      name: authentification-service-secrets
      namespace: prod

