image:
  repository: ghcr.io/elhadj-cloud-lab/authentification_service
  tag: dev-5465d44

replicaCount: 1

javaOpts: ""

env:
  - name: SPRING_DATASOURCE_URL
    value: jdbc:postgresql://postgres-auth-postgresql:5432/auth_db
  - name: SPRING_DATASOURCE_USERNAME
    value: auth_user
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres-auth-credentials
        key: password
  - name: JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: authentification-service-secrets
        key: jwt-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
