image:
  repository: ghcr.io/elhadj-cloud-lab/authentification_service
  tag: prod-4f77081

replicaCount: 2

javaOpts: ""

env:
  - name: SPRING_DATASOURCE_URL_USER
    value: jdbc:postgresql://postgres-auth-postgresql:5432/auth_db
  - name: SPRING_DATASOURCE_USERNAME
    value: auth_user
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres-auth-credentials
        key: password
  - name: JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: authentification-service-secrets
        key: jwt-secret

initContainers:
  - name: wait-for-db
    image: busybox:1.36
    command:
      - sh
      - -c
      - >-
        echo Waiting for postgres-auth-postgresql:5432...;
        for i in $(seq 1 120); do
          nc -z postgres-auth-postgresql 5432 && exit 0;
          sleep 2;
        done;
        echo DB not reachable;
        exit 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
