apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-auth-credentials
  namespace: prod
spec:
  encryptedData:
    password: AgCvYZuX8gkt46/j27C9b9vM5CTdbXhznSBnIGnDz13bLpfFBqkUHwOtlOYcydPoMQiTOS+T6zeiPxKzgEpDGtqhNoeDzGTyKc8stbUVZLikIIoCH5Dh7oMujRyCozceu9m3TGwtf/4HBnkLBuYtxcYCgzzeersi9zG40VmeVdQ8CFEj+xhuBurQf9VSKre4ipgqQuSLlNGnDLxHN9n5y3HCQX24Ve5dNxeB7GottBGMIKZOWhn8ZM0c1uuO7F/eKN+KJVNjcdxmw8NtQbnSgepYl4k+H4o4EjsoMaXoUhXW7UPeLquS4Lnm6+m9vmoFsGM6hMTUJBgsBpo4ualwgySVsTpPYBWnrs80l0de3ukh27bHcnTePVvRt0kSeiyF0lGw/J0g1PwIPFv+j4i9F9SzE7QHpSL5yOHbfSLWDE2gT5n/X0TK2g+JskGxBit6yfqpkrkPXaYS/2dtAytH4EfBepFiaaqYq5LGeCEt2UX3wY30+DogSjFk5SBuIEGBw9K2Dy/wo4oBaFyRl7i2V2v9JCHzDsFGQaahM+bf2iDYcjfmkSbtA8PxycTH6FpoKWllcNFvVdH/BuyEhYt8pyOAA4oJOoi+i1xzPcx+l5vISrHMeYDsqSEQQyhELoBpf2Z7LNUxpVcU4FMbGUixSdqyS2NW8FY+BJ1d7MKWIsln3TQDN+KP/1s9NJeNc3DFxrTKf4QxxLYpSBCHWVPtsYL1aAWMZE0+
    postgres-password: AgC2agJMxTgjcSjHel/wKQnzfkx9V3AlNJvIGefbufA7uowScoEusqA8yV9dQ2lxtxCFLwL6TA4IPHQf9vbGTPXZuQW3IwZIJ45Ilj2018oSbH/BUt5/j7GmMRM0Q+PVju0DLdS45Ib+RWzPlspQUqahgi6cg04p5Rf+0LlEVFD6IwM5mSaGnoa8tMyl2ijE1qDZlYoJjQAXdVTQ3rk/j83iNdjJ4FG9/6cxDzdRIZd4vfsXBAh+wCcyJe92WFnv2+EM3JCDGCMUdYec6qQdDuYh3D9Vzj1zR1IgKg3kXPUQ+N2Ic7vQhs7eL1gm8CeKc0QJZZ2lNXX3gVygNI5iuUdy67qdo36Dns0mfJ+1Kr9jaRNJAyHID/1mSMvA7uEIjgirZfs71Un/aWC/Hgu/IGlYVa2EoA2ncvmuIylz2hIkYI5DwDhFlGrj/2yeD3WLpXrXqHMGg8f05trmQ4SAjbpAa0ekzwtF2l1nBqUBmL5x+USga5KCF0rdmuvklelRS6P1sFe/pFE9+JK0mVpf0e9rMqk89v1tKqYt4l7dvs9RiWFAqQ5ccVcTs47FyTJht52rDXeCADLcrkClmnW7uZk3wrCcZ2uEbD0u0C2e+gQn4hd63r/hGyPuQWzVGEMSQ2Wnd2xQFldGqDUp19fjQr0PkFk308vOd4sdU/OdjasZhutZ1ivieVBkeeAGb1ZkHidAR/PfuqPCs0WveE6n3LdhjL/h7UaY
  template:
    metadata:
      creationTimestamp: null
      name: postgres-auth-credentials
      namespace: prod

