apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-auth-credentials
  namespace: dev
spec:
  encryptedData:
    password: AgBtF3Y+w+stgQsQcI3xmVYM7wMsBRhKhycEejQ7y0qBMgbHTL/SBGocG7J31d8ovVk6XrieVZMJpTOeq0p4nf/uoIRKbrLXAFpALwKHmHgabrHNPmy8yPiYF7avQKjvM+9B93uzg1io9W9KA6nbxyYZ+369+6N4WKJUYTnPCC/6ufuzF1Zqjy1e7QsSOTSUSycp6hJ9T1eS2XwG688bIT8bDcau6Fv3Kx3592oUYFxN4yzAHUIx1dsIIo9D6M7yjaFgscn/9Ab86y4KsrCMtzjD/2qUkqa2YpZHVypBc22I2GECn8xms8Xe9MYI5VjJ1MPfboaxgKQrmizFcv9wKhvMSVdSX+L975gdGslnwOhw7mI7L2tsAPnOkt0MU9mdb1gIfB4w78MbbHhIflph3MBT2eXeh7jqY5ftGKna5YWxostfsZeveTUOqjFgCmHKNuK26seu2tIH8imnqrWPvT4agTC9EM7yUtBk8RoOlf2GEgXPoRgioRk5rxerePNi5wDNKSqrZ7Sd7XKWQdcJE+uiSs13RNlxfhkBL3He74H3BIlMVpsOWhhL2xI6ZJ/tm2+t4v0SguNB7pJJhoUPnmRI/thEGDPhKJhnxWlqVPy1KDWU9kCKrQXEogJaiMevbfxHvYWkfjws6dnoSNo7WLdT67LXm9+2KeM9pQRdnUi2fUIVg6Vg7Gk3NYs1X5Y1bYoBwH7+cRmK82YUQ/Bw9EVM2myE6/8=
    postgres-password: AgAILSOd3jm7Lv75Gwn119RIXwUwokvZ2AYnNtwvUPfzuCjY1+MuxeUs/TX50WrcSkwAVX+t6nv7kaZUwUH77UsHrAzwp1rld0iuyFlNRscK2IPTwB+ZffKoZ+XCejYa83mXrRH5bAGZgqzp/q0ZgOunPYsO4CSFDjDJiPWhl5d5e7EMWrdz7tf6DLM2yB2MpvTb9+AC7TcD9/g64HY0ihBYIZ4OAqAEX3jtxyh6LGACCH0vikzA7bWkmFVNNBVgWy/+EI/6n7iX4Rps4xndMPszty93GLtf/HHHkova5jiyXyZ6m2ns25tGSMRKa6J+ycG92oIPpxCbsyCa2PZuTsgVH27OifelvXzPYGTS7ndiomJA6yskmGVbiD7lp9ukjtkgo+7RHaBLS4aFvoV+by0LPJ+5pdMHLtkU0hmQzjjag92laZcOfSStOnc0OcqGR83pOayerwISTFAsUF4jHDsNRovoqQLBDins5K6sgu6dNwL6+K8J56oWNJ9oh8sQMLerB2cesGVm6xlJq8VQBvCahh9CmIC0IjAAcKyXOjYAqDwNIx6tVEGBB103UCwfQB0Kxi1e/viouzXMrl8ZziBDsFoEkZPFuVSDsquvv8NQOjpzJsMABFSMr3qDDkqA2SvLYEYuV7swQUaMDY7l7x9kDpowiBqnaxSR+hf+OygtQpirZIBVlwOqkBH7LqgqmGJl3GgSkkcIicJAFrLrUIznZTsD08E=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-auth-credentials
      namespace: dev

