auth:
  username: auth_user
  database: auth_db
  existingSecret: postgres-auth-credentials

image:
  tag: 16.4.0-debian-12-r0

volumePermissions:
  enabled: true

primary:
  persistence:
    enabled: true
    size: 1Gi
  containerSecurityContext:
    readOnlyRootFilesystem: false
  extraVolumes:
    - name: postgresql-run
      emptyDir: {}
  extraVolumeMounts:
    - name: postgresql-run
      mountPath: /var/run/postgresql
