apiVersion: v1
kind: Service
metadata:
  name: postgres-produit
  labels:
    app.kubernetes.io/name: postgres-produit
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
  selector:
    app.kubernetes.io/name: postgres-produit
