apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-produit-credentials
  namespace: dev
spec:
  encryptedData:
    password: AgBNU28dcWqjtk/aRJPKzf+/r8Xyt5oaixUHOyax5kP0r7uYNW1l+bP+TExQlyTxyuJQdZbC9GIQBDldOiSh4nIMtUXbOeeNoqrih8GK2sj9PLjT/4nsj3mEo9ziJfNBxb5mV4s9p+HWIuL4KdRj6ZtJFNvoOVo3rHnSP/EFNxHZr4rAvS/cJc26Euzg9/Vx9ADu14XS8TVVR32VEAVQ0ILcBjzPJQtIIhEY6p1HaOP/JQnHsAZzauJR7SoUbzIDU7Wn9zlibJPzJj5VfMC30d+3npqViuhr8/m0H1/6TnJ1gXNQirWktCWahS9bhLrtMSQd6FRADrqew7I6bOVU+iM5f6buLUT3mlmTgUipOEAfthCJYT85kiXXDqTEiim2/j1X1Du06WGh4tGpAWsGYMuCp5Ao8vOmLXWZggsQ6ylCwkYuLxNepPDd0E5jVVsHmZ8rshZw0Lu3lhURBvupaFErfRXjsf3qCYRa13IpZi8nRdFKUB85bleNrJwjgUmoVNGIq9XpHhnUrO5D9Dv/DEHeF4NPES0MAEwTRGMb610XzeeTuNGwyw/YWwpxu5Ksq/K4SQ5IPYjv8kuFznAmVzjQAiF2TBUC/PX4PupkBfJijqKQkVfPU0ztHpHh17SnbUesF6OJYdLIf96rs/9Teoafu7ObjfI84dkNJdBD1ybeTw0K1ODDvfuvKiWwriAkoJgguC2al0hQ/RZi9wMaI/i/LOiOE4SNPqw=
    postgres-password: AgCAPUwLrQjBn+EON0uM2I7BHmp+fUB0ZZzIQpW9+S4rrV58GA7m+QtNbFdPSVCPREd4G3qfzmp7tMxN+H0oMWDMJWASr110zkv/665ndAHrm9prBAPDZJmZcQxkT22Ce8Tqe5WD0wVkn0nTBjjyRbl838CwA5qFf4zgttnRM1b0AvJwbG75GL1OQd9kqK6Yx3rc7wJBrU+nNIVtvQHvZdo9w2nlEk/u1lFOQ7V7dSQ5KzVzxZ8pgcehsS/A9eXub/LVpSjd9t37wmGmqSG/kvXMgwvwWFHSW70JFF+MPlZIpO3WOWXmTfxfQoMiHHJ5JfrH4MJn6rSXTKqjqvWfsEYIdOrl2S212YluuJW5j0hlqZf/pk+KLIEG/64gELaYVKhtYdyI8i5tTbQoJXCssEwGb6zQc9iwM7TKwXeEgz+fFYfapxDWmR29qdlSlfGd9mK2+m6DtFyEagtoIF9Jz+ai1pXWhacR6qbYX6+MGPoJFcQin3soWYg2R7U7ZQCvNWeUm03dA81hfu7R7U/cJ0CIyVUUIc0TLNy4GCEXeRR8hlrvenJNfz/SMuu3nXYDqXxkf5gmHefFKxP8nN8suJc0BaU7SJy41SUoAGa0ZDU5iFwnPFb73vCx8j6WlolEZ/S60KRvdhOhF/8qsvj9/LN5wIGl1sLItb5oGNB1nPBELl+hhgg/Azu96bVQoKYjNk2fYDY072jJwfGDtlWlt8VUHqBuPBC0Bfs=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-produit-credentials
      namespace: dev

