apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-produit-credentials
  namespace: prod
spec:
  encryptedData:
    password: AgCx6WG/SK0OtvFFYA9wturLtktqSZ6R8orepYZud5j8GfeAcaoJuc+t+emNIoRu/NWJgzn0G16tYgsZcIr/kYmKryErYRrj19LBG7lEbeSbGBcmJpia8QXPwYRTjQ34Krgslv6Fy8QY6UuttjxqrEQRq0Ih1pT9sIWYSv+fIqOekMkV2qfJMD4iV6rUA2nOUvPwy2ZT+ZyQlZjb3ztxFQT5QawFGNwTUYBnqQ1Sa3R7/iGRGUUCdp//G3AqNwRGkIrS2FIk4SkruQssj72+6tYSG4UXyPCszNBCKtedCydsZghFJ+nDTuiXXcME6igZPIwYDrfh+L+QNaXxkxg5qwdQQyezwnGICcpl3nX/CvnghzZbnNhX97lslIMQEq3ixFOqN/YbbqVz1BDLZ/R6smGgtOkit/PcVyr/DOZ4UPcgaCVvQsB31Nl9OCwzaHiqfdJjLMms4cOD+P5xJ6JdZjHCSU/MDJ6GPNfU5DP3XYjtUrO7EG7j8QFgpXsRl6iJBBt+DVHrVaEG/gStWkOFfHfe7fZCRGWPAApUQ/Pf2Xh1O2L29mXLGAh7gHXFFgcV6hwCYopPNj0zfZhJfLLWrY+S0JFbDv793d4N7aNPuUSAHHY90V9+FtD7qZNchyCaNAMR0Zju+a/7B8dOCIHk+w5K1fOGde6E+9S3HvXKGTYLCB/OatuU4zBfvDuLssxumJ//0vb+F85RnsA3SMh4QTMzLOaV/eLE2ebo
    postgres-password: AgALY/ooUc2iPlDnF6aoz82leETYqlWpdL0gXF0dFCgtoxEbhFHtWXRcyYrZzpixBup7WxKfnl9eCAgGf4ISzogGm8MxTX6siZL8aYtXLv/qn+Ah2Ma1sW+UMyhvvYnnu+zRPShn2xV3yNSc5Y9Wj54/8I2MLq6XNi+wqodveUz1lH0IgyNiAtXlCFBd4krwz5CqBw/u+sNQPFQY5+co4bYbnIkPwrI9H4/oa7WENko5I9SAdbOxj+lPadVNAiMmU8IkX2oC90ymkB54IGdETvXIrNbKyAFWM5wHZaPWw1OULECDTRs2vrCuUAzrAJGdUBtuvHMTcU1O5xBLknHbbDdloWjVezrd5008KRl79KEpy063FnUnUrYmRzPTD8chJrkfw4mTiKTzeBqKf+iUwO3Jo1FchmuEMe/LLnKw3Eg6vStRYZT9bVtJi6oVlxemBE7xDFzWqdoCR5+SQSQZvr8dzAOIdyEYmQ5cE36twKQh4IiepHrLjYPnN4zBtZNlENmYWM0mrt9KZNQxfIBHvuZ24G3cFb0m8bIMbLdPbyoyVTRXN7IIhPIQzzzLHRTNz91IxsmCoh0DPZ3IUxQTRV5CtfckE3+LRtnlPCfxhH1Ws3aoIzkDw9ixVjbxjsKq0AgQG8rkLAGDpxQhyal3v3gELcBVY//ixq6Zl8c55/bExSel+zDJVTHeAZPBOKMfBYbXvwXld0UxBWv2mPiqbK2c8mrKJkaxeLTc
  template:
    metadata:
      creationTimestamp: null
      name: postgres-produit-credentials
      namespace: prod

