apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/elhadj-cloud-lab/deployment_k8s.git
    targetRevision: main
    path: apps/secrets/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
