replicaCount: 1

image:
  repository: ghcr.io/elhadj-cloud-lab/produit_back
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

containerPort: 8080

env: []

resources: {}
