image:
  repository: ghcr.io/elhadj-cloud-lab/produits_front
  tag: latest

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "false"
  host: "produits.dev.bestech.com"
  pathType: Prefix
  backend:
    serviceName: produit-back
    servicePort: 80
